### ISSUE TITLE
ica-sdk not working with latest versions of typing extensions (4.14.0)

### ISSUE THREAD

**Issue by Alexander-Stuckey** [Illumina/ica-sdk-python#6]
`ica-sdk` has a requirement on `tpying-extensions~=4.3.0`, however the latest version is now `4.14.0`. It is also incompatible with this version. I believe it works with versions up to `4.13.0`

```
File "/usr/local/lib/python3.10/site-packages/icasdk/api_client.py", line 1278, in Api
    def _verify_typed_dict_inputs_oapg(cls: typing.Type[typing_extensions.TypedDict], data: typing.Dict[str, typing.Any]):
  File "/usr/local/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/typing.py", line 1143, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/local/lib/python3.10/typing.py", line 1143, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/local/lib/python3.10/typing.py", line 171, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing_extensions.TypedDict is not valid as type argument
```

Are there any plans to update the sdk to support later versions of `typing-extensions`?

**Comment by Alexander-Stuckey** [comment]
In fact, downgrading to `4.3.0` also throws an error
```
...
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 153, in <module>
    from exceptiongroup import BaseExceptionGroup
  File "/usr/local/lib/python3.10/site-packages/exceptiongroup/__init__.py", line 15, in <module>
    from ._catch import catch
  File "/usr/local/lib/python3.10/site-packages/exceptiongroup/_catch.py", line 11, in <module>
    from ._exceptions import BaseExceptionGroup
  File "/usr/local/lib/python3.10/site-packages/exceptiongroup/_exceptions.py", line 10, in <module>
    from typing_extensions import TypeVar
ImportError: cannot import name 'TypeVar' from 'typing_extensions' (/usr/local/lib/python3.10/site-packages/typing_extensions.py)
```
I've only had it working with `typing-extensions==4.12.0`, which pip thinks is incompatible.

**Comment by alexiswl** [comment]
@Alexander-Stuckey this repo has never worked and appears to have been abandoned by Illumina. 

Please checkout our repos - https://github.com/umccr/libica and https://github.com/umccr/wrapica for python sdks of the ICAv2 platform
